# Generated by Django 3.2.8 on 2021-10-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='unlikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - very poor'), (2, '2 - poor'), (3, '3 - Terrible'), (4, '4 -good'), (5, '5 -very good'), (6, '6 -perfect'), (7, '7 -Exellent'), (8, '8-world class')]),
        ),
    ]
