# Generated by Django 3.2.8 on 2021-10-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_auto_20211024_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
