# Generated by Django 3.2.8 on 2021-10-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20211024_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='developer',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='averangeRating',
        ),
    ]
